spring:
  application:
    name: database-design
  datasource:
    url: jdbc:mysql://localhost:3306/database-design
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: @YOUR_PASSWORD@
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false

